# Generated by Django 3.2.11 on 2022-01-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_userprofile_working_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='education_status',
            field=models.CharField(blank=True, choices=[('1', 'Tələbəyəm'), ('2', 'Tələbə deyiləm')], default=0, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='university',
            field=models.CharField(blank=True, choices=[('1', 'Ada Universiteti'), ('2', 'Azərbaycan Əmək və Sosial Münasibətlər Akademiyası'), ('3', 'Azərbaycan Milli Konservatoriyası'), ('4', 'Azərbaycan\xa0Dillər\xa0Universiteti'), ('5', 'Azərbaycan\xa0Dövlət\xa0Aqrar\xa0Universiteti')], default=0, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='working_status',
            field=models.CharField(blank=True, choices=[('1', 'İşləyirəm'), ('2', 'İşləmirəm')], default=0, max_length=2, null=True),
        ),
    ]
